// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/groups/[groupId]/index.ts";
import * as $2 from "./routes/api/groups/[groupId]/ogiris/[ogiriId]/answer.ts";
import * as $3 from "./routes/api/groups/[groupId]/ogiris/[ogiriId]/report.ts";
import * as $4 from "./routes/api/groups/[groupId]/ogiris/new.ts";
import * as $5 from "./routes/api/groups/[groupId]/users/add.ts";
import * as $6 from "./routes/api/groups/create.ts";
import * as $7 from "./routes/api/hc/index.ts";
import * as $8 from "./routes/api/test.ts";
import * as $9 from "./routes/api/users/create.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/groups/[groupId]/index.ts": $1,
    "./routes/api/groups/[groupId]/ogiris/[ogiriId]/answer.ts": $2,
    "./routes/api/groups/[groupId]/ogiris/[ogiriId]/report.ts": $3,
    "./routes/api/groups/[groupId]/ogiris/new.ts": $4,
    "./routes/api/groups/[groupId]/users/add.ts": $5,
    "./routes/api/groups/create.ts": $6,
    "./routes/api/hc/index.ts": $7,
    "./routes/api/test.ts": $8,
    "./routes/api/users/create.ts": $9,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
