// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/groups/[groupId]/index.ts";
import * as $2 from "./routes/api/groups/[groupId]/ogiris/[ogiriId]/answer.ts";
import * as $3 from "./routes/api/groups/[groupId]/ogiris/[ogiriId]/report.ts";
import * as $4 from "./routes/api/groups/[groupId]/ogiris/index.ts";
import * as $5 from "./routes/api/groups/[groupId]/ogiris/new.ts";
import * as $6 from "./routes/api/groups/[groupId]/ogiris/now.ts";
import * as $7 from "./routes/api/groups/[groupId]/users/create.ts";
import * as $8 from "./routes/api/groups/create.ts";
import * as $9 from "./routes/api/hc/index.ts";
import * as $10 from "./routes/api/patch/scoring.ts";
import * as $11 from "./routes/api/patch/status.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/groups/[groupId]/index.ts": $1,
    "./routes/api/groups/[groupId]/ogiris/[ogiriId]/answer.ts": $2,
    "./routes/api/groups/[groupId]/ogiris/[ogiriId]/report.ts": $3,
    "./routes/api/groups/[groupId]/ogiris/index.ts": $4,
    "./routes/api/groups/[groupId]/ogiris/new.ts": $5,
    "./routes/api/groups/[groupId]/ogiris/now.ts": $6,
    "./routes/api/groups/[groupId]/users/create.ts": $7,
    "./routes/api/groups/create.ts": $8,
    "./routes/api/hc/index.ts": $9,
    "./routes/api/patch/scoring.ts": $10,
    "./routes/api/patch/status.ts": $11,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
